### ISSUE TITLE
Advanced Online installation network check

### ISSUE THREAD

**Issue by DeltaCopy** [arcolinux/arcolinux-welcome-app-dev#1]
Since the **Advanced Online installation** option depends on a working internet connection and the Arco/Arch mirrors needs to be accessible. An idea is to add a connection test, as soon as a user clicks on the Advanced Online install button.

This way any issues are reported to the user quicker, and not when Calamares is in the middle of installing packages - which is too late since the user has already spent a lot of time going through the pre-installation process.

To test connectivity issues I made a change to the `/etc/hosts` file to simulate a DNS issue, added `0.0.0.0 gitlab.com` `0.0.0.0 github.com` `0.0.0.0 mirror.rackspace.com` so this makes the DNS lookup fail.

Two tests are carried out:

- Curl request for the core.db file
- Pacman sync db `pacman -Sy`

Tested on a Live ISO, and here are a few pictures of what it looks like.

# Console output

![vm_test_console_err](https://github.com/arcolinux/arcolinux-welcome-app-dev/assets/121581829/efd2ab56-3758-4173-9c82-e5ce8917583b)

# Message dialog

![vm_test_msdialog_err](https://github.com/arcolinux/arcolinux-welcome-app-dev/assets/121581829/6ce87092-bda4-4814-93cd-5a3ebdbc5af7)

# Pacman sync db

![vm_test_pacman_sync_err](https://github.com/arcolinux/arcolinux-welcome-app-dev/assets/121581829/a4c1bb83-c2cd-42bd-b936-514548edc617)

# Curl connection
![vm_test_curl_err](https://github.com/arcolinux/arcolinux-welcome-app-dev/assets/121581829/33fce6a1-04d1-4e7d-945f-ebf267989fce)

**Comment by arcolinuxz** [comment]
ok
